### ISSUE TITLE
[Feature Request] Optional customizable landing page

### ISSUE THREAD

**Issue by versx** [WatWowMap/MapJS#148]

**Comment by PartTimeJS** [comment]
How customizable do you want the landing page? This kind of thing gets difficult when people have multiple discords and such. In my situation, i use subdomain identification to determine which discord they are/should be a part of.

**Comment by versx** [comment]
You aren't the only one to mention that to me using sub domain for which Discord, I believe Dergel does too and possible a few others so that might be the best way to go about this. Personally I only have one sub domain for the map but definitely interested in possibly setting it up based on multiple sub domains.

Although we can find the Discord based on authentication (if they are in multiple and have access, show all areas from any they have access to). I think this might be good coupled with area restrictions per Discord.

I'm still indecisive with how to restrict areas, I'd rather not clutter SQL queries with geometry, it's the only thing I can think of other than manually checking each item if it's within the specified geofences (outside of sql). Maybe we need to import geofences into tables now. :thinking:
