### ISSUE TITLE
Bug: Stardust limit

### ISSUE THREAD

**Issue by clburlison** [WatWowMap/MapJS#187]
Quests > Disable All > Enable stardust filter "1000" enable startdust quest.

The above works perfectly.

Quests > Disable All > manually enable all Misc options > Enable stardust filter "1000" enable startdust quest.

Limit does not work. Likely a minor sql bug somewhere?

**Comment by versx** [comment]
Looks like it's the unused XP filter that causes the issues.

**Comment by versx** [comment]
I suggest we just remove the unnecessary/unused quest filters until they are used in the game itself.

**Comment by Mygod** [comment]
> I suggest we just remove the unnecessary/unused quest filters until they are used in the game itself.

Wtf? First wtf is with the defeatist attitude? Also I cannot reproduce this bug. Did you refresh?

**Comment by versx** [comment]
If it does nothing, then how it is a feature? I'm not saying to remove the code, just comment out the ids that aren't used.

I'm able to reproduce the bug. This is after it's saved.
![image](https://user-images.githubusercontent.com/1327440/94058024-59658000-fd95-11ea-87ff-896a53360389.png)
