### ISSUE TITLE
Feat: nests

### ISSUE THREAD

**Issue by clburlison** [WatWowMap/MapJS#189]
Would like to have distinguishing indicator around Pokémon nest icon. Any visual preferences from community? I don't think a glow is a good choice since that might confuse 100% Pokémon.

![7CE6D99F-E49C-4961-92F7-8EB9CF459AC2](https://user-images.githubusercontent.com/2831320/93027690-54097800-f5d4-11ea-84ff-f90e2afdcfc7.jpeg)
![879F4637-FE53-4092-843D-5AB5AA23F691](https://user-images.githubusercontent.com/2831320/93027691-55d33b80-f5d4-11ea-8a13-41a00304d305.jpeg)

**Comment by Mygod** [comment]
My thought: opacity ~0.5 and show 3 copies of them diagonally.

**Comment by versx** [comment]
> My thought: opacity ~0.5 and show 3 copies of them diagonally.

Three copies of the nesting Pokemon or the background nest icon?

**Comment by Mygod** [comment]
Oh I guess if you have a background nest icon then probably just need one copy of the pokemon. :joy:

**Comment by clburlison** [comment]
webhook test

**Comment by versx** [comment]
I could have sworn I added the nesting species type icons underneath the nest Pokemon icons to help distinguish them a bit. 🤔

**Comment by sketchysocks** [comment]
They were definitely there at one point

**Comment by versx** [comment]
I bet @Mygod deleted it 😜

**Comment by Mygod** [comment]
WATWOW

**Comment by Mygod** [comment]
Never mind it was me because it looks ugly af. I probably forgot to include it in my PR description (it should be in one of those where I redo pokemon icons).
