### ISSUE TITLE
Importing an old JSON config without portal filter causes the map to freeze

### ISSUE THREAD

**Issue by Mygod** [WatWowMap/MapJS#249]
It seems like `portal_filter` is set to `"undefined"`.

```
jquery.min.js:2 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadStorage (index.js:940)
    at HTMLDocument.<anonymous> (index.js:198)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
```

**Comment by versx** [comment]
Duplicate #140

**Comment by Mygod** [comment]
My memory is failing me

**Comment by Mygod** [comment]
No wait this is different because it is specifically regarding portals.

**Comment by versx** [comment]
> No wait this is different because it is specifically regarding portals.

Right but that's because it doesn't exist (in the old export)? Same as importing an old json, which some values might not exist such as some quests/raids.

If we provide defaults for those non-existent filter values upon import I think we'd be good?

**Comment by Mygod** [comment]
Yes I think backwards compatibility should be considered.
