### ISSUE TITLE
Translate Marker Popup Content

### ISSUE THREAD

**Issue by versx** [WatWowMap/MapJS#258]
Needs locale translations for marker popup content text.

**Comment by lenisko** [comment]
https://github.com/WatWowMap/MapJS/blob/b7ff01c6aa6f78d10c40bc49843aacd79b4bad3f/static/js/index.js#L5784
https://github.com/WatWowMap/MapJS/blob/b7ff01c6aa6f78d10c40bc49843aacd79b4bad3f/static/js/index.js#L5786
https://github.com/WatWowMap/MapJS/blob/b7ff01c6aa6f78d10c40bc49843aacd79b4bad3f/static/js/index.js#L5854
https://github.com/WatWowMap/MapJS/blob/b7ff01c6aa6f78d10c40bc49843aacd79b4bad3f/static/js/index.js#L5867
https://github.com/WatWowMap/MapJS/blob/b7ff01c6aa6f78d10c40bc49843aacd79b4bad3f/static/js/index.js#L5880

I think that's all 🤔

**Comment by lenisko** [comment]
https://github.com/WatWowMap/MapJS/pull/350

**Comment by lenisko** [comment]
+ https://github.com/WatWowMap/MapJS/pull/356

**Comment by TurtIeSocks** [comment]
Closing this as I believe #356 covered it.
