### ISSUE TITLE
[Feature Request] Show map version

### ISSUE THREAD

**Issue by versx** [WatWowMap/MapJS#278]
Show map version somewhere, user never really needs to see it so somewhere in one of the menus might be best, perhaps the settings page.

**Comment by TurtIeSocks** [comment]
Can we just stick it at the top of index.js as a variable? Not visible to public. Easily accessible if we're trying to help a map admin troubleshoot.

**Comment by versx** [comment]
Yeah that works, I think using `package.json`'s `version` property might be better but definitely a solution.
