### ISSUE TITLE
[Bug] Enabling pokestops in main filter causes map to ignore quest reward filters

### ISSUE THREAD

**Issue by PartTimeJS** [WatWowMap/MapJS#300]
Steps to reproduce:
1. Enable quests only
2. Set filters to hide specific quest rewards. Save
3. Enable pokestops

All quest rewards will show regardless of reward filters. Users request that stops still be visible, but without the rewards that are filtered out.

**Comment by versx** [comment]
Pretty sure this is intended behavior since they are enabling all Pokestops. If they disable Normal Pokestops in the sub-menu it'll hide them.
