### ISSUE TITLE
[Feature Request] Show raid timers on the map 

### ISSUE THREAD

**Issue by lenisko** [WatWowMap/MapJS#314]
Show raid timers on the map (same way it's implemented on pmsf).

This might impact overall performance a bit but is also very critical to efficiency plan a raids.
An option to enable/disable from user side would be great.

**Comment by versx** [comment]
![image](https://user-images.githubusercontent.com/1327440/105439598-ffc57300-5c19-11eb-9f38-e882f774da51.png)

**Comment by lenisko** [comment]
:facepalm:

**Comment by Mygod** [comment]
I've also received complaints that the settings are too hard to find.

**Comment by lenisko** [comment]
@Mygod yeah that was straight from the user. But I didn't even noticed this settings pop-up myself :joy:
