### ISSUE TITLE
Unused script leaflet-easyprint

### ISSUE THREAD

**Issue by lenisko** [WatWowMap/MapJS#334]
https://github.com/WatWowMap/MapJS/blob/d3972afbd92ad6b1d592ce693e54d25b8fbd7a06/src/views/header.mustache#L28

Can't find any usage. Is it needed?

**Comment by versx** [comment]
> https://github.com/WatWowMap/MapJS/blob/d3972afbd92ad6b1d592ce693e54d25b8fbd7a06/src/views/header.mustache#L28
> 
> Can't find any usage. Is it needed?

Not sure why that's referenced tbh 🤔 it's used to export map data, but we don't currently use it.

**Comment by lenisko** [comment]
In this case, lets kill it with :fire:
