### ISSUE TITLE
Configure button broken on latest

### ISSUE THREAD

**Issue by Shyvadi** [WatWowMap/MapJS#398]
![image](https://user-images.githubusercontent.com/22157510/179327667-e7105b2d-d9a0-4d05-bc8c-6c8270d7840e.png)
![image](https://user-images.githubusercontent.com/22157510/179327681-aaff481e-8066-43b1-ac6f-f704148514fe.png)
getting this in console log

**Comment by versx** [comment]
@Shyvadi 
🤔 I'm assuming this is the Pokemon IV `AND` and `OR` configure buttons?
Both look to be working for me (Quest and next configure buttons as well), try clearing your browser cache for the website to see if that fixes it. Based on the error I'm going to guess it's trying to load no longer valid cached filter settings.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1327440/179328288-8a390d8d-55e8-4eb9-904f-bc1d8a789afb.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1327440/179328333-34e92408-78e3-4af3-808b-ec644e992d3a.png">

**Comment by Shyvadi** [comment]
Clear cache fixed issue, thanks

**Comment by versx** [comment]
> Clear cache fixed issue, thanks

Glad to hear!

**Comment by Shyvadi** [comment]
Reopening because the issue is reoccuring

**Comment by versx** [comment]
> Reopening because the issue is reoccuring

rip

**Comment by versx** [comment]
> Reopening because the issue is reoccuring

@Shyvadi Is it all of the Configure buttons or just a specific one? Check Pokemon, Nests, and Quests if you can, please.
Also post a screenshot of any errors thrown in the dev console if possible.

**Comment by Shyvadi** [comment]
I'm certain it's cache. Closing issue for good this time (for sure)
